services:
  api:
    build:
      context: ./backend
      target: base
    container_name: fastapi-app
    env_file:
        - ./backend/.env
    ports:
      - '8000:8000'
    restart: "always"
  web:
    build:
      context: ./frontend
      target: web
    container_name: react-app
    env_file:
        - ./frontend/.env
    depends_on:
      - api
    ports:
      - '9000:9000'